{ pkgs, ... }:

let
  # Auto-generated by scripts/update-vscode-extensions.py. Edit
  # ./extensions/sources.json (and rerun the script) instead of this file.
  extensionSpecs = import ./extensions/generated.nix;

  mkMarketplaceExtension =
    spec:
    spec
    // {
      drv = pkgs.vscode-utils.buildVscodeMarketplaceExtension {
        mktplcRef = {
          inherit (spec) publisher name version sha256;
        };
      };
    };
in {
  extensions = map mkMarketplaceExtension extensionSpecs;
}
